#REVISAR PASWORDS, KEYS, DATABASE_URL Y NETWORK
#LEVANTAR CON (SUDO) docker compose up -d --build

services:
  docuseal:
    build: .
    container_name: docuseal
    restart: always
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "3000:3000"
    environment:
      - HOSTNAME=vota.ucmxlapublica.org
      - PROTOCOL=https
      - DATABASE_URL=postgresql://postgres:EXAMPLE@db:5432/docuseal
      - RAILS_ENV=production
      - RAILS_SERVE_STATIC_FILES=true
      - SECRET_KEY_BASE=PONERAQUI
    volumes:
      - ./data:/data/docuseal
    networks:
      - porlapublica

  db:
    image: postgres:18
    container_name: docuseal-db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=PONERPASWWORD
      - POSTGRES_DB=docuseal
    volumes:
      - ./pg_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d docuseal"]
      interval: 10s
      timeout: 5s
      retries: 5
    # Crear la tabla del censo al arrancar si no existe
    command: >
      sh -c "docker-entrypoint.sh postgres & 
      sleep 10; 
      psql -U postgres -d docuseal -c 'CREATE TABLE IF NOT EXISTS votos_presenciales (email TEXT PRIMARY KEY, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);'; 
      wait"
    networks:
      - porlapublica
    #App del censo
  censo:
    build: ./censo-app
    container_name: censo-ucm
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://postgres:EXAMPLE@db:5432/docuseal
    ports:
      - "5001:5000"
    networks:
      - porlapublica

networks:
  porlapublica:
    external: true
